{{ if .Capabilities.APIVersions.Has "kyverno.io/v2alpha1/PolicyException" }}
apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: {{ include "external-secrets.name" . }}-crd
  namespace: "{{ .Release.Namespace }}"
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-3"
    {{- include "crdInstallAnnotations" . | nindent 4 }}
  labels:
    {{- include "external-secrets.labels" . | nindent 4 }}
spec:
  background: true
  exceptions:
  - policyName: disallow-host-path
    ruleNames:
    - host-path
    - autogen-host-path
    - autogen-cronjob-host-path
  - policyName: require-run-as-nonroot
    ruleNames:
    - run-as-non-root
    - autogen-run-as-non-root
    - autogen-cronjob-run-as-non-root
  - policyName: restrict-volume-types
    ruleNames:
    - restricted-volumes
    - autogen-restricted-volumes
    - autogen-cronjob-restricted-volumes
  - policyName: disallow-capabilities-strict
    ruleNames:
    - require-drop-all
    - adding-capabilities-strict
    - autogen-require-drop-all
    - autogen-cronjob-require-drop-all
    - autogen-adding-capabilities-strict
    - autogen-cronjob-adding-capabilities-strict
  - policyName: restrict-seccomp-strict
    ruleNames:
    - autogen-check-seccomp-strict
  - policyName: disallow-privilege-escalation
    ruleNames:
    - autogen-privilege-escalation
  match:
    any:
    - resources:
        kinds:
        - Job
        names:
          - "external-secrets*"
        namespaces:
        - "{{ .Release.Namespace }}"
{{- end }}
