{{- if and .Values.certController.create .Values.certController.podDisruptionBudget.enabled (not .Values.webhook.certManager.enabled) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
<<<<<<< HEAD
  name: {{ include "external-secrets.name" . }}-cert-controller-pdb
  namespace: {{ .Release.Namespace | quote }}
||||||| 6361e801
  name: {{ include "external-secrets.fullname" . }}-cert-controller-pdb
  namespace: {{ .Release.Namespace | quote }}
=======
  name: {{ include "external-secrets.fullname" . }}-cert-controller-pdb
  namespace: {{ template "external-secrets.namespace" . }}
>>>>>>> 7038e0fcc5dba6dd8deab143fea1c8b335eaeabe
  labels:
    {{- include "external-secrets-cert-controller.labels" . | nindent 4 }}
spec:
  {{- if .Values.certController.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.certController.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.certController.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.certController.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "external-secrets-cert-controller.selectorLabels" . | nindent 6 }}
{{- end }}
