{{- if .Capabilities.APIVersions.Has "cilium.io/v2/CiliumNetworkPolicy" }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "external-secrets.name" . }}-access-apiserver
  labels:
    {{- include "external-secrets.labels" . | nindent 4 }}
spec:
  egress:
  - toEntities:
    - kube-apiserver
    - cluster
    - world
  ingress:
  - fromEntities:
    - kube-apiserver
    - cluster
  endpointSelector:
    matchLabels:
{{ include "external-secrets.selectorLabels" . | indent 6 }}
{{- end }}
