{{- if .Capabilities.APIVersions.Has "cilium.io/v2/CiliumNetworkPolicy" }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "external-secrets.name" . }}-access-apiserver
  labels:
    {{- include "external-secrets.labels" . | nindent 4 }}
spec:
  egress:
  - toEntities:
    - kube-apiserver
    - cluster
    - world
  endpointSelector: {}
{{- else }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "external-secrets.name" . }}-access-apiserver
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "external-secrets.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  # allow egress traffic to the Kubernetes API
  egress:
    - ports:
        - port: 443
          protocol: TCP
        # legacy port kept for compatibility
        - port: 6443
          protocol: TCP
      to:
    {{- range tuple "10.0.0.0/8" "172.16.0.0/12" "192.168.0.0/16" "100.64.0.0/10" }}
        - ipBlock:
            cidr: {{ . }}
    {{- end }}
  policyTypes:
    - Egress
{{- end }}
