{{- if .Values.metrics.service.enabled }}
apiVersion: v1
kind: Service
metadata:
<<<<<<< HEAD
  name: {{ include "external-secrets.name" . }}-metrics
  namespace: {{ .Release.Namespace | quote }}
||||||| 6361e801
  name: {{ include "external-secrets.fullname" . }}-metrics
  namespace: {{ .Release.Namespace | quote }}
=======
  name: {{ include "external-secrets.fullname" . }}-metrics
  namespace: {{ template "external-secrets.namespace" . }}
>>>>>>> 7038e0fcc5dba6dd8deab143fea1c8b335eaeabe
  labels:
    {{- include "external-secrets.labels" . | nindent 4 }}
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  {{- if .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  {{- end }}
  {{- if .Values.service.ipFamilies }}
  ipFamilies: {{ .Values.service.ipFamilies | toYaml | nindent 2 }}
  {{- end }}
  ports:
    - port: {{ .Values.metrics.service.port }}
      protocol: TCP
      targetPort: metrics
      name: metrics
  selector:
    {{- include "external-secrets.selectorLabels" . | nindent 4 }}
{{- end }}
