{{- if .Values.webhook.create }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: secretstore-validate
  labels:
    external-secrets.io/component: webhook
<<<<<<< HEAD
    {{- with .Values.commonLabels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- if and .Values.webhook.certManager.enabled .Values.webhook.certManager.addInjectorAnnotations }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "external-secrets.name" . }}-webhook
  {{- end }}
||||||| 6361e801
=======
    {{- with .Values.commonLabels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- if and .Values.webhook.certManager.enabled .Values.webhook.certManager.addInjectorAnnotations }}
  annotations:
    cert-manager.io/inject-ca-from: {{ template "external-secrets.namespace" . }}/{{ include "external-secrets.fullname" . }}-webhook
  {{- end }}
>>>>>>> 7038e0fcc5dba6dd8deab143fea1c8b335eaeabe
webhooks:
- name: "validate.secretstore.external-secrets.io"
  rules:
  - apiGroups:   ["external-secrets.io"]
    apiVersions: ["v1beta1"]
    operations:  ["CREATE", "UPDATE", "DELETE"]
    resources:   ["secretstores"]
    scope:       "Namespaced"
  clientConfig:
    service:
<<<<<<< HEAD
      namespace: {{ .Release.Namespace | quote }}
      name: {{ include "external-secrets.name" . }}-webhook
||||||| 6361e801
      namespace: {{ .Release.Namespace | quote }}
      name: {{ include "external-secrets.fullname" . }}-webhook
=======
      namespace: {{ template "external-secrets.namespace" . }}
      name: {{ include "external-secrets.fullname" . }}-webhook
>>>>>>> 7038e0fcc5dba6dd8deab143fea1c8b335eaeabe
      path: /validate-external-secrets-io-v1beta1-secretstore
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  timeoutSeconds: 5

- name: "validate.clustersecretstore.external-secrets.io"
  rules:
  - apiGroups:   ["external-secrets.io"]
    apiVersions: ["v1beta1"]
    operations:  ["CREATE", "UPDATE", "DELETE"]
    resources:   ["clustersecretstores"]
    scope:       "Cluster"
  clientConfig:
    service:
<<<<<<< HEAD
      namespace: {{ .Release.Namespace | quote }}
      name: {{ include "external-secrets.name" . }}-webhook
||||||| 6361e801
      namespace: {{ .Release.Namespace | quote }}
      name: {{ include "external-secrets.fullname" . }}-webhook
=======
      namespace: {{ template "external-secrets.namespace" . }}
      name: {{ include "external-secrets.fullname" . }}-webhook
>>>>>>> 7038e0fcc5dba6dd8deab143fea1c8b335eaeabe
      path: /validate-external-secrets-io-v1beta1-clustersecretstore
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  timeoutSeconds: 5
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: externalsecret-validate
  labels:
    external-secrets.io/component: webhook
<<<<<<< HEAD
    {{- with .Values.commonLabels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- if and .Values.webhook.certManager.enabled .Values.webhook.certManager.addInjectorAnnotations }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "external-secrets.name" . }}-webhook
  {{- end }}
||||||| 6361e801
=======
    {{- with .Values.commonLabels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- if and .Values.webhook.certManager.enabled .Values.webhook.certManager.addInjectorAnnotations }}
  annotations:
    cert-manager.io/inject-ca-from: {{ template "external-secrets.namespace" . }}/{{ include "external-secrets.fullname" . }}-webhook
  {{- end }}
>>>>>>> 7038e0fcc5dba6dd8deab143fea1c8b335eaeabe
webhooks:
- name: "validate.externalsecret.external-secrets.io"
  rules:
  - apiGroups:   ["external-secrets.io"]
    apiVersions: ["v1beta1"]
    operations:  ["CREATE", "UPDATE", "DELETE"]
    resources:   ["externalsecrets"]
    scope:       "Namespaced"
  clientConfig:
    service:
<<<<<<< HEAD
      namespace: {{ .Release.Namespace | quote }}
      name: {{ include "external-secrets.name" . }}-webhook
||||||| 6361e801
      namespace: {{ .Release.Namespace | quote }}
      name: {{ include "external-secrets.fullname" . }}-webhook
=======
      namespace: {{ template "external-secrets.namespace" . }}
      name: {{ include "external-secrets.fullname" . }}-webhook
>>>>>>> 7038e0fcc5dba6dd8deab143fea1c8b335eaeabe
      path: /validate-external-secrets-io-v1beta1-externalsecret
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  timeoutSeconds: 5
  failurePolicy: {{ .Values.webhook.failurePolicy}}
{{- end }}
