apiVersion: v2
name: external-secrets
description: External secret management for Kubernetes
type: application
version: "0.4.3"
appVersion: "v0.8.1"
kubeVersion: ">= 1.19.0-0"
keywords:
  - kubernetes-external-secrets
  - secrets
home: https://github.com/giantswarm/external-secrets
icon: https://s.giantswarm.io/app-icons/external-secrets/1/light.svg
annotations:
  application.giantswarm.io/team: "honeybadger"
  config.giantswarm.io/version: 1.x.x
restrictions:
  clusterSingleton: true
  namespaceSingleton: true
